---
########################################################################################

- name: Test mount {{ accessMode }} volumes for {{ prefix }}
  kubernetes.core.k8s:
    state: present
    namespace: "{{ storage_validation_namespace }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  loop:
     - name: create-volume.yaml.j2

########################################################################################
# FILE UID Write/Read
########################################################################################
- name: Set config maps
  kubernetes.core.k8s:
    state: present
    namespace: "{{ storage_validation_namespace }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  loop:
     - name: producer-cm.yaml.j2
     - name: consumer-cm.yaml.j2

- name: set up scc and sa for fsgroup test
  block:
    - name: create custom scc
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'fsgroup-scc.yaml.j2') | from_yaml }}"
    - name: create custom sa
      shell: oc create sa uid-sa -n {{ storage_validation_namespace }}
    - name: add scc to custom sa
      shell: oc adm policy add-scc-to-user zz-fsgroup-scc system:serviceaccount:{{ storage_validation_namespace }}:uid-sa 
  rescue:
    - debug:
        msg: "set up scc and sa for file uid test failed"

- name: File uid create {{ accessMode }} volumes for {{ prefix }}
  kubernetes.core.k8s:
    state: present
    namespace: "{{ storage_validation_namespace }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
    wait: yes
    wait_timeout: 180
    wait_condition:
      type: Complete
      status: "True"
  loop:
     - name: file-owner-uid-test.yaml.j2
     - name: file-create-uid.yaml.j2
     - name: file-edit-uid.yaml.j2
  vars:
    type: uid

# - name: get uid
#   shell: oc logs $(oc get pods -l name=file-uid-job -n {{ storage_validation_namespace }} -o name) -n {{ storage_validation_namespace }} | tail -3 | head -1
#   register: create_uid 

# - name: Display create_uid
#   debug: msg="{{ create_uid.stdout | string }}"

- debug:
    msg: "######################## FILE UID TEST PASSED FOR {{ accessMode }} Volume #################################"
