---
########################################################################################

########################################################################################
# Mount Test
########################################################################################

- name: set up scc and sa for fsgroup test
  block:
    - name: create custom scc
      k8s:
        state: present
        definition: "{{ lookup('template', 'fsgroup-scc.yaml.j2') | from_yaml }}"
    - name: create custom sa
      shell: oc create sa fsgroup-sa -n {{ storage_validation_namespace }}
    - name: add scc to custom sa
      shell: oc adm policy add-scc-to-user fsgroup-scc system:serviceaccount:{{ storage_validation_namespace }}:fsgroup-sa  
  rescue:
    - debug:
        msg: "set up scc and sa for fsgroup test failed"
  when: accessMode == 'ReadWriteOnce'
  
- name: Test mount {{ accessMode }} volumes for {{ prefix }}
  k8s:
    state: present
    namespace: "{{ storage_validation_namespace }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  loop:
     - name: create-volume.yaml.j2
     - name: mount-job.yaml.j2

- name: Verify mount completed for {{ accessMode }}
  k8s_info:
    name: "{{ prefix }}-mount-job-{{ accessMode|lower}}"
    namespace: "{{ storage_validation_namespace }}"
    kind: Job
  register: job_status
  until: job_status.resources[0].status.succeeded is defined and job_status.resources[0].status.succeeded == 1
  retries: 20
  delay: 10

- debug: 
    msg: "######################## MOUNT TESTS PASSED FOR {{ accessMode }} Volume  #################################"
