---
########################################################################################

- name: Test mount {{ accessMode }} volumes for {{ prefix }}
  k8s:
    state: present
    namespace: "{{ storage_validation_namespace }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  loop:
     - name: create-volume.yaml.j2

########################################################################################
# Sequential Write/Read
########################################################################################
- name: Set config maps
  k8s:
    state: present
    namespace: "{{ storage_validation_namespace }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  loop:
     - name: producer-cm.yaml.j2
     - name: consumer-cm.yaml.j2

- name: Sequential read/write {{ accessMode }} volumes for {{ prefix }}
  k8s:
    state: present
    namespace: "{{ storage_validation_namespace }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
    wait: yes
    wait_timeout: 180
    wait_condition:
      type: Complete
      status: "True"
  loop:
     - name: producer.yaml.j2
     - name: consumer.yaml.j2
  vars:
    type: sequential

- debug:
    msg: "######################## SEQUENTIAL READ WRITE TEST PASSED FOR {{ accessMode }} Volume #################################"
