---
# Run sysbench test
- name:  Run sysbench random read RWX test
  k8s:
    state: present
    definition: "{{ lookup('template', 'sysbench_random_read_rwx.yaml.j2') }}"

- name: Wait X seconds/minutes for tests to run
  pause:
    minutes: 10

- name: Get logs of the sysbench random read pod for RWX
  community.kubernetes.k8s_log:
    namespace: "{{ storage_perf_namespace }}"
    label_selectors:
    - job-name=sysbench-random-read-rwx
  register: logx

- name: Save Log to local file
  local_action:
    module: copy
    content: "{{ logx }}"
    dest: "{{ logfolder }}/random_read_rwx.json"
