---
# Run sysbench test
- name:  Run sysbench sequential write rwo test
  k8s:
    state: present
    definition: "{{ lookup('template', 'sysbench_sequential_write_rwo.yaml.j2') }}"

- name: Wait X seconds/minutes for tests to run
  pause:
    minutes: 10

- name: Get logs of the sysbench sequential write pod for RWO
  community.kubernetes.k8s_log:
    namespace: "{{ storage_perf_namespace }}"
    label_selectors:
    - job-name=sysbench-sequential-write-rwo
  register: logo

- name: Save sequential write Log to local file
  local_action: 
    module: copy 
    content: "{{ logo }}"
    dest: "{{ logfolder }}/sequential_write_rwo.json"