---
# Run sysbench test
- name:  Setup PVCs to run test on
  k8s:
    state: present
    definition: "{{ lookup('template', 'common-objects.yaml.j2') }}"

- name: Create logs directory
  ansible.builtin.file:
    path: '{{ logfolder }}'
    state: directory
    mode: '0755'

- name: Wait X seconds/minutes for tests to run
  pause:
    seconds: 5